### ISSUE TITLE
Error al enviar la planificador externo

### ISSUE THREAD

**Issue by fraromesc** [alvcaballero/multiuav_gui#4]
{
    "loc": [
        {
            "geo_points": [
                {
                    "lat": 37.0173394635042,
                    "lon": -6.56117745155808
                },
                {
                    "lat": 37.0183971060858,
                    "lon": -6.56082608217713
                }
            ],
            "name": "prueba1"
        }
    ],
    "meteo": [
        {
            "humidity": 24.2,
            "lat": 37.1417181974,
            "lon": -6.4568362063,
            "pressure": 101860.0,
            "temp": 24.2,
            "wind_dir": 0.0,
            "wind_vel": 0.0
        }
    ],
    "mission_id": 97,
    "objetivo": 0
}

**Comment by arpoma16** [comment]
Luego de revisar este errlor no corresponde, ya que es un error del planificador.

**Comment by arpoma16** [comment]
Luego de revisar este errlor no corresponde, ya que es un error del planificador.
